### ISSUE TITLE
question about using safenetwork-webapi with SolidAuthClient.fetch()

### ISSUE THREAD

**Issue by ghost** [theWebalyst/safenetwork-webapi#1]
Hi Mark,
Thank you for doing this.  I don't know much about SAFE yet and this is maybe a naive question.  I want to try SAFE with my Solid code, but my Solid code uses SolidAuthClient.fetch(), from the solid-auth-client package, instead of rdflib.fetch(), because I wanted to decouple the fetch from the serialization/deserialization and reasoning that rdflib.js does.  Is there an easy way to use SolidAuthClient.fetch() with safenetwork-webapi?  Thanks.

**Comment by happybeing** [comment]
I haven't looked at SolidAuthClient at all yet so there may be dragons 😉, but...

I see no reason why you can't replace SolidAuthClient.fetch exactly the same way I did for rdflib.js

See Fetcher.js in my fork of rdflib.js. It just checks to see if the replacement fetch is there (in rdf.appFetch) and if it does uses that instead of the Fetcher.fetch. Also, in your app, make sure you file the usage example for rdflib.js, in your use of SolidAuthClient. Good luck! 

Let me know how you get on and if you need any help. I'd like to see if I can make the auth work on SAFE or Solid with a forked SolidAuthClient but very busy just now so don't know when I'll get time to look at that.

**Comment by happybeing** [comment]
One more thing, please use the wip branch until I merge those changes to master:

https://github.com/theWebalyst/safenetwork-webapi/tree/wip

**Comment by ghost** [comment]
Yeah auth in general is over my head, so I'm hoping that dragon eventually turns out to be friendly 😄.  It may be a while before I can get to looking into it, but when I do I'll probably borrow some code from solid-yo, which I think also uses solid-auth-client and window.fetch().  I'm still learning Javascript though, so I need to figure out exactly what solid-yo is doing.

**Comment by happybeing** [comment]
OK, I'll close this for now but just reopen it if you come back to this, and good luck. 

In case it offers inspiration I'm still learning JavaScript, and writing this library is the culmination of my trying to make something useful for SAFE Network, bit by bit, over the last two years. JavaScript is hard at times, but worth it 😸
